# Generated by Django 5.2.7 on 2025-12-22 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_old_cart',
        ),
    ]
