# Generated by Django 5.2.7 on 2025-12-20 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_date_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 20, 14, 38, 16, 587172)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='IRAN', max_length=25),
        ),
    ]
