# Generated by Django 5.2.7 on 2025-12-20 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_profile_old_cart_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 20, 18, 12, 31, 353932)),
        ),
    ]
